### ISSUE TITLE
Auto-parsed window title contains markup

### ISSUE THREAD

**Issue by rkiesler1** [mashery/blackbeard#124]
See xpologistics.mashery.com -- looks like the window title is parsed dynamically from the content of the \<h1\> tag on the page, which contains additional markup (\<b\>). The result:

![image](https://user-images.githubusercontent.com/7738591/30842535-b554a88a-a237-11e7-935c-c121660b6557.png)

The text should be "sanitized" of any markup before used for a window title.

**Comment by cferdinandi** [comment]
**Note for me:** Use innerText instead of innerHTML for title setting

**Comment by cferdinandi** [comment]
Fixed
