### ISSUE TITLE
Typo in instructions of using custom fonts

### ISSUE THREAD

**Issue by rkiesler1** [mashery/blackbeard#125]
The code example in https://stagingcs1.mashery.com/docs/read/extras/Loading_Custom_Fonts include this line:

`sessionStorage.addItem('portalFontsLoaded')`

However, this results in a runtime error, as the session object has no such method. Instead, the following works as expected:

`sessionStorage.setItem('portalFontsLoaded', true);  // 2nd argument required, can be any value`

**Comment by cferdinandi** [comment]
Updated. I removed session storage altogether, since it's not necessary with Ajax loading, and added better dependency management.
