### ISSUE TITLE
Access user Apps & API on custom pages

### ISSUE THREAD

**Issue by maximehabibi** [mashery/blackbeard#149]
Hi,

We are looking to implement a custom page "Report Issue" where our APIs consumers could send tickets about the problem(s) they encountered.

For doing so we would like to implement a dropdown list of plans & / or APIs concerned. We did not find yet how to access these user variables ( Plans & APIs on which they are subscribed ).

Any piece of information about this subject would be great ! ( I personally did not find anything in the official Mashery documentation ) 

Thanks ! 👍

**Comment by cferdinandi** [comment]
Hello again! I love this idea!

First off, you'll want to [verify that the user is logged in by checking `mashery.loggedIn`](https://developer.mashery.com/docs/read/customizing_your_portal/mashery_portal_2_documentation/Style_and_Script_Hooks#script-hooks). This property returns a boolean, `true` if they're logged in.

```js
if (mashery.loggedIn) {
    // the user is logged in
    // we can query the APIs they have access to
}
```

There's no official JS APIs/methods yet for getting a list of APIs, packages, and plans that the user has access to, but that's a great idea and I'm going to open a ticket for it!

In the meantime, we can use the included [Atomic ajax helper library](https://developer.mashery.com/docs/read/customizing_your_portal/mashery_portal_2_documentation/JavaScript_API#atomicajax) to call the user's account page and get a list of their APIs and plans.

```js
// Remove duplicate plans/APIs from the list
// source: https://codehandbook.org/how-to-remove-duplicates-from-javascript-array/
var removeDuplicates = function (arr){
	var uniqueArray = arr.filter(function(elem, index, self) {
		return index == self.indexOf(elem);
	});
	return uniqueArray;
};

// Get the user's APIs
atomic.ajax({
	url: '/apps/myapps',
	responseType: 'document'
}).success(function (data) {
	// The `data` variable is an HTML document you can search using querySelector/querySelectorAll

	// An empty array that we'll push our plan names to
	var plans = [];
	
	// Get all li elements from the page (they contain the info about the specific APIs)
	var items = data.querySelectorAll('#main .section-body .application tbody tr td');

	// Loop through each item, and if it contains an API/Plan name, push it to the `plans` array
	items.forEach(function (item) {
		
		// Skip items that don't have a plan name
		if (!/API: /.test(item.innerHTML)) return;

		// Push the plan name to the plans array
		plans.push(item.innerHTML.replace('API: ', '').trim());

	});

	// Remove any duplicate plans from the array
	plans = removeDuplicates(plans);

	// Generate your dropdown from the list of plans
	console.log(plans);

}).error(function () {
	// If the request fails, perhaps fallback to an empty text field instead?
});
```

Let me know if that helps!

**Comment by maximehabibi** [comment]
Thank you for your detailed and well explained answer Chris, that helped me a lot.

The only point you got wrong is on the Regex Pattern, `/API: /` returns no item as the document is not structured like that. The matching pattern is 12 white spaces (cannot write it directly here, github does not render it correctly!)

It is actually how it's done as the number of space is recurrent on the elements ( sorry, found it yesterday evening but at the moment I do not manage to find the pattern in the content.main anymore... the structure is complicated! )
You can just try it with: 
```
if (!/            /.test(item.innerHTML)) return;

// Push the plan name to the plans array
plans.push(item.innerHTML.replace('            ', '').trim());
```

Many thanks again !

**Comment by cferdinandi** [comment]
@maximehabibi Sorry about that! I tested this on https://developer.mashery.com and it worked. I wonder what differs about your setup.

Is it ok if I close this out?

**Comment by maximehabibi** [comment]
Sure
